### PR TITLE
Feat/alluvial charts r 5.0.6

### PR DESCRIPTION
**Pull request by chris-demartini**
This PR Adds: 

* Alluvial Diagram
* charts-R package (visachartR wrapper in R)
* repo wide testing and audit scripts
* dependency clean up
* accessibility util refactor
* clustered-bar-chart unit tests

### CODE REVIEW

**Comment by chris-demartini** [comment]
Hi @frank-elavsky, 

Here are unit testing results, matching snapshot and thus expectations. 

 PASS  scripts/test-results.spec.tsx
  <jest-test-report>
    ✓ test errors should match what we had before (193ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        1.669s
Ran all test suites matching /scripts\/test-results.spec.tsx|compare-test-results/i.

**Comment by frank-elavsky** [comment]
Perfect, thanks Chris.

**Comment by chris-demartini** [comment]
Here is the results for dependency audit check as well, also matching expectation. Note I will post one more commit which has a few changes in the audit result snapshot, but these are not related to audit results, just dependency counts, etc. 

 PASS  scripts/audit-results.spec.tsx
  <yarn-audit-results>
    ✓ audit results should match what we had before, and be clean (31ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        1.222s
Ran all test suites matching /scripts\/audit-results.spec.tsx|compare-audit-results/i.

**Comment by frank-elavsky** [comment]
Once the commit is up, we can merge. Thanks Chris!

**Pull request merged**
